# Generated by Django 4.0.1 on 2022-02-22 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans', models.TextField()),
                ('like_count', models.IntegerField(default=0)),
                ('dislike_count', models.IntegerField(default=0)),
                ('ans_askedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quesasked', to=settings.AUTH_USER_MODEL)),
                ('ans_toques', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ans_toques', to='app.question')),
            ],
        ),
    ]
