# Generated by Django 4.0.1 on 2022-04-11 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_comment_ques_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('ans_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='getallans', to='app.answer')),
                ('comment_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_towhich_comment', to='app.comment')),
                ('ques_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_which_ques', to='app.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='getall_user_toreply', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
