# Generated by Django 4.0.1 on 2022-04-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='created',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
